//
// Created by janha on 14/03/2024.
// Documentation Generated by Jetbrains AI
//

#ifndef MEP_RBO_H
#define MEP_RBO_H



#include "GL/glew.h"


class RBO {
public:
    GLuint ID;
    /**
     * @brief The RBO class represents a Render Buffer Object.
     *
     * The RBO class is responsible for managing a Render Buffer Object (RBO) in OpenGL.
     *
     * A Render Buffer Object is an OpenGL object that stores an image or a set of images used for rendering operations.
     * This class provides methods for creating, binding, unbinding, clearing, and resizing the RBO.
     */
    RBO();
    /**
     * @brief Create a render buffer object with the specified width and height.
     *
     * This function creates a render buffer object (RBO) with the specified width and height.
     * The object ID will be generated using glGenRenderbuffers.
     *
     * @param width The width of the RBO.
     * @param height The height of the RBO.
     */
    void RBO_create(int width, int height);

    /**
     * @brief Binds the render buffer object.
     *
     * This function binds the render buffer object using OpenGL command glBindRenderbuffer.
     */
    void bind();
    /**
     * @brief Unbinds the renderbuffer object.
     *
     * When called, this function unbinds the current renderbuffer object. This means that the
     * subsequent rendering operations will no longer affect the renderbuffer.
     *
     * @see RBO::bind()
     */
    void unbind();
    /**
     * @brief Clears the renderbuffer object.
     *
     * This function deletes the renderbuffer object using OpenGL function glDeleteRenderbuffers.
     *
     * @note This function does not affect the bound renderbuffer.
     */
    void clear();
    /**
     * @brief Resizes the storage of the render buffer object.
     *
     * This function resizes the storage of the render buffer object to the specified width and height.
     *
     * @param width The new width of the render buffer.
     * @param height The new height of the render buffer.
     */
    void resizeStorage(int width, int height);
};


#endif //MEP_RBO_H
